activities/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings

from .views import (
    ScheduleHiddenView, ScheduleRealView, ActivityView, ActivitySubscribeView, ActivityEditView, ProposalView, ProposalSentView
)


def user_is_staff(user):
    return user.is_staff


if settings.SCHEDULE_HIDDEN:
    urlpatterns = [
        # Option initial (schedule is hidden, visible only to admin)
        url(r'^programa$', ScheduleHiddenView.as_view(), name='schedule'),
        url(r'^programa-desarrollo$', user_passes_test(user_is_staff)(ScheduleRealView.as_view()), name='schedule-devel'),
    ]
else:
    urlpatterns = [
        # Option normal (schedule is publicly visible)
        url(r'^programa$', ScheduleRealView.as_view(), name='schedule'),
    ]

urlpatterns += [
    url(r'^actividad/(?P<activity_id>\d+)$', ActivityView.as_view(), name='activity'),
    url(r'^actividad-inscribir/(?P<activity_id>\d+)$', login_required(ActivitySubscribeView.as_view()), name='activity-subscribe'),
    url(r'^actividad-editar/(?P<activity_id>\d+)$', login_required(ActivityEditView.as_view()), name='activity-edit'),
    url(r'^propuesta$', login_required(ProposalView.as_view()), name='proposal'),
    url(r'^propuesta-enviada$', login_required(ProposalSentView.as_view()), name='proposal-sent'),
]

user_profiles/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings

from .views import (
    PreSignupView, SignupView, LoginView, LogoutView, ForgotPasswordView, ChangePasswordView,
    UserProfileView, UserProfileEditPersonalView, UserProfileEditInscriptionView,
    UserListingsIndexView, UserListingView
)

def user_is_staff(user):
    return user.is_staff

if settings.PRE_SIGNUP_FORM:
    # Option initial (pre signup form only send mail to admins, does not create real users)
    urlpatterns = [
        url(r'^inscripcion$', PreSignupView.as_view(),
            name='signup')
    ]
else:
    urlpatterns = [
        url(r'^inscripcion$', SignupView.as_view(),
            name='signup')
    ]

urlpatterns += [
    url(r'^entrada$', LoginView.as_view(),
        name='login'),
    url(r'^salida$', LogoutView.as_view(),
        name='logout'),
    url(r'^olvido$', ForgotPasswordView.as_view(),
        name='forgot-password'),
    url(r'^cambiar$', ChangePasswordView.as_view(),
        name='change-password'),
    url(r'^ficha$', login_required(UserProfileView.as_view()),
        name='user-profile'),
    url(r'^ficha-editar-personal$', login_required(UserProfileEditPersonalView.as_view()),
        name='user-profile-edit-personal'),
    url(r'^ficha-editar-inscripcion$', login_required(UserProfileEditInscriptionView.as_view()),
        name='user-profile-edit-inscription'),
    url(r'^listados$', user_passes_test(user_is_staff)(UserListingsIndexView.as_view()),
        name='user-listings-index'),
    url(r'^listados/(?P<listing_id>\d+)$', user_passes_test(user_is_staff)(UserListingView.as_view()),
        name='user-listing'),
]

user_profiles/models.py
from django.db import models
from django.contrib.auth.models import User

from random import choice
import string


class UserProfile(models.Model):
    # Link with the Django user
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)

    # Additional info
    alias = models.CharField('pseudónimo', max_length=100, blank = True)
    smial = models.CharField('smial', max_length=100, blank = True)
    phone = models.CharField('teléfono', max_length=100)
    city = models.CharField('población', max_length=100)
    age = models.IntegerField('edad')
    dinner_menu = models.CharField('Menú de la cena de gala', max_length=50, blank = True,
        choices=(
            ('carne', 'Carne'),
            ('pescado', 'Pescado'),
            ('otros', 'Otros'),
        )
    )
    notes_food = models.TextField('Comentarios comida', blank = True)  # (vegetariano, celiaco...)
    day_1 = models.BooleanField('Asistencia viernes/sábado', default=True)
    day_2 = models.BooleanField('Asistencia sábado/domingo', default=True)
    day_3 = models.BooleanField('Asistencia domingo/lunes+cena', default=True)
    notes_transport = models.TextField('Comentarios transporte', blank = True)  # (medio de transporte, hora de llegada...)
    room_choice = models.CharField('Elige un tipo de alojamiento', max_length=50,
        choices=(
            (
                'Habitación compartida', (
                    ('compartida-completa', '(compartida) completa'),
                    ('compartida-v-a-d', '(compartida) viernes a domingo'),
                    ('compartida-s-y-d', '(compartida) sábado y domingo'),
                )
            ),(
                'Habitación individual', (
                    ('individual-completa', '(individual) completa'),
                    ('individual-v-a-d', '(individual) viernes a domingo'),
                    ('individual-s-y-d', '(individual) sábado y domingo'),
                )
            ),
            ('otros', 'Otros'),
        )
    )
    room_preferences = models.TextField('¿Tienes alguna preferencia sobre con quién compartir habitación?', blank = True)
    children_count = models.IntegerField('¿Traes niños a tu cargo? Si es así, indica cuántos', default=0)
    children_names = models.TextField('Indica sus nombres, uno en cada línea', blank = True)
    is_ste_member = models.BooleanField('¿Eres socio/a de la STE?', default=True)
    want_ste_member = models.BooleanField('En caso de que no, ¿quieres asociarte por 2€ más?', default=False)
    squire = models.BooleanField('¿Quieres ser escudero?', default=False)
    first_estelcon = models.BooleanField('¿Es tu primera Estelcon?', default=False)
    want_mentor = models.BooleanField('¿Querrías participar en el programa de mentorazgo a nuevos asistentes?', default=False)
    want_media = models.BooleanField('Autorizo el uso de material audiovisual generado durante el evento Mereth Aderthad 2019 en donde se me pueda identificar por parte de la Sociedad Tolkien Española en su labor de difusión de actividades', default=False)
    notes_general = models.TextField('Comentarios general', blank = True)
    shirts_S_1 = models.IntegerField('Camisetas talla S (1)', default=0)
    shirts_M_1 = models.IntegerField('Camisetas talla M (1)', default=0)
    shirts_L_1 = models.IntegerField('Camisetas talla L (1)', default=0)
    shirts_XL_1 = models.IntegerField('Camisetas talla XL (1)', default=0)
    shirts_XXL_1 = models.IntegerField('Camisetas talla XXL (1)', default=0)
    shirts_S_2 = models.IntegerField('Camisetas talla S (2)', default=0)
    shirts_M_2 = models.IntegerField('Camisetas talla M (2)', default=0)
    shirts_L_2 = models.IntegerField('Camisetas talla L (2)', default=0)
    shirts_XL_2 = models.IntegerField('Camisetas talla XL (2)', default=0)
    shirts_XXL_2 = models.IntegerField('Camisetas talla XXL (2)', default=0)
    shirts_S_3 = models.IntegerField('Camisetas talla S (3)', default=0)
    shirts_M_3 = models.IntegerField('Camisetas talla M (3)', default=0)
    shirts_L_3 = models.IntegerField('Camisetas talla L (3)', default=0)
    shirts_XL_3 = models.IntegerField('Camisetas talla XL (3)', default=0)
    shirts_XXL_3 = models.IntegerField('Camisetas talla XXL (3)', default=0)
    quota = models.IntegerField('Cuota')
    payed = models.IntegerField('Pagado')
    payment = models.TextField('Estado de pago') # (u'pendiente de pago', u'pago confirmado', <texto de problema>)
    lost = models.CharField('(dato interno)', max_length=50, blank=True)   # For lost password recovery

    class Meta:
        verbose_name = 'Ficha de usuario'
        verbose_name_plural = 'Fichas de usuario'
        ordering = ('id',)

    def __str__(self):
        return self.user.username + ' - ' + self.user.email + ' - ' + self.user.get_full_name() + ' - ' + self.payment[:40] + '...'

    @property
    def payment_code(self):
        return 'EC%d' % (self.user.id + 100)

    @property
    def is_under_age(self):
        return (self.age < 18)

    def get_admin_url(self):
        from django.conf import settings
        from django.core.urlresolvers import reverse
        return settings.PROTOCOL + '://' + settings.SITE_URL + \
                reverse('admin:auth_user_change', args=(self.user.id,))

    def generate_reminder_code(self):
        chars = string.ascii_letters + string.digits
        self.lost = ''.join([choice(chars) for i in range(50)])

    def reset_reminder_code(self):
        self.lost = ''

user_profiles/views.py
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView
from django.contrib.auth import login, logout
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.conf import settings
from django.http import HttpResponseNotFound, HttpResponseForbidden

from . import services

from .forms import (
    PreSignupForm, SignupForm, LoginForm, ForgotPasswordForm, ChangePasswordForm,
    UserProfileEditPersonalForm, UserProfileEditInscriptionForm
)


class PreSignupView(FormView):
    template_name = 'user_profiles/signup_off.html'
    form_class = PreSignupForm

    def form_valid(self, form):
        services.pre_register_user(
            user_data = form.cleaned_data,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        return super(PreSignupView, self).form_valid(form)

    def get_success_url(self):
        messages.info(self.request, 'Se ha enviado tu preinscripción a los organizadores, en breve se pondrán en contacto contigo.')
        return '/index.html'


class SignupView(FormView):
    template_name = 'user_profiles/signup.html'
    form_class = SignupForm

    def get_context_data(self, **kwargs):
        context = super(SignupView, self).get_context_data(**kwargs)
        context['signup_closed'] = settings.SIGNUP_CLOSED
        return context

    def post(self, request, *args, **kwargs):
        if not settings.SIGNUP_CLOSED:
            return super(SignupView, self).post(request, *args, **kwargs)
        else:
            # If signup form disabled, don't process anything and return the same page
            return super(SignupView, self).get(request, *args, **kwargs)

    def form_valid(self, form):
        (user, queue) = services.create_new_user(
            user_data = form.cleaned_data,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        self.user = user
        self.queue = queue
        return super(SignupView, self).form_valid(form)

    def get_success_url(self):
        profile = self.user.profile
        return reverse('login') + '?payment_code=%s&quota=%d&queue=%d' % (
            profile.payment_code,
            profile.quota,
            self.queue,
        )


class LoginView(FormView):
    template_name = 'user_profiles/login.html'
    form_class = LoginForm
    success_url = reverse_lazy('user-profile')

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)

        context['payment_code'] = self.request.GET.get('payment_code', '')
        context['quota'] = self.request.GET.get('quota', 0)
        try:
            context['queue'] = int(self.request.GET.get('queue', 0))
        except ValueError:
            context['queue'] = 0

        return context

    def form_valid(self, form):
        login(self.request, form.cleaned_data['user'])
        return super(LoginView, self).form_valid(form)


class LogoutView(TemplateView):
    template_name = 'user_profiles/logout.html'

    def get(self, *args, **kwargs):
        logout(self.request)
        return super(LogoutView, self).get(*args, **kwargs)


class ForgotPasswordView(FormView):
    template_name = 'user_profiles/forgot_password.html'
    form_class = ForgotPasswordForm
    success_url = reverse_lazy('forgot-password')

    def form_valid(self, form):
        services.send_password_reminder(
            user = form.cleaned_data['user'],
            change_password_url_pattern = settings.PROTOCOL + '://' + settings.SITE_URL +
                reverse('change-password') + '?reminder_code=%s',
        )
        messages.info(self.request, 'Se ha enviado a tu dirección de correo un mensaje con instrucciones para crear una nueva contraseña.')
        return super(ForgotPasswordView, self).form_valid(form)


class ChangePasswordView(FormView):
    template_name = 'user_profiles/change_password.html'
    form_class = ChangePasswordForm
    success_url = reverse_lazy('user-profile')

    def get_initial(self):
        return {
            'reminder_code': self.request.GET.get('reminder_code', '')
        }

    def form_valid(self, form):
        services.change_user_password(
            user = form.cleaned_data['user'],
            password = form.cleaned_data['password1']
        )
        messages.info(self.request, 'Tu contraseña ha sido cambiada. Ya puedes entrar con ella.')
        return super(ChangePasswordView, self).form_valid(form)


class UserProfileView(TemplateView):
    template_name = 'user_profiles/user_profile.html'

    def get_context_data(self, **kwargs):
        context = super(UserProfileView, self).get_context_data(**kwargs)

        user = self.request.user
        context['profile'] = user.profile
        context['owned_by'] = services.get_activities_owned_by(user)
        context['organized_by'] = services.get_activities_organized_by(user)
        context['participant_in'] = services.get_activities_in_which_participates(user)
        if not settings.SCHEDULE_HIDDEN:
            context['activities_to_participate'] = services.get_activities_to_participate_by(user)
        else:
            context['activities_to_participate'] = []

        return context


class UserProfileEditPersonalView(FormView):
    template_name = 'user_profiles/user_profile_edit_personal.html'
    form_class = UserProfileEditPersonalForm
    success_url = reverse_lazy('user-profile')

    def get_initial(self):
        user = self.request.user
        profile = user.profile
        return {
            'username': user.username,
            'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'alias': profile.alias,
            'smial': profile.smial,
            'phone': profile.phone,
            'city': profile.city,
            'age': profile.age,
        }

    def form_valid(self, form):
        services.change_user_personal_data(
            user = self.request.user,
            new_data = form.cleaned_data,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        messages.info(self.request, 'Datos modificados correctamente')
        return super(UserProfileEditPersonalView, self).form_valid(form)


class UserProfileEditInscriptionView(FormView):
    template_name = 'user_profiles/user_profile_edit_inscription.html'
    form_class = UserProfileEditInscriptionForm
    success_url = reverse_lazy('user-profile')

    def get_initial(self):
        user = self.request.user
        profile = user.profile
        return {
            'notes_food': profile.notes_food,
            'dinner_menu': profile.dinner_menu,
            'notes_transport': profile.notes_transport,
            'room_choice': profile.room_choice,
            'room_preferences': profile.room_preferences,
            'squire': profile.squire,
            'notes_general': profile.notes_general,
            'shirts_S_1': profile.shirts_S_1,
            'shirts_M_1': profile.shirts_M_1,
            'shirts_L_1': profile.shirts_L_1,
            'shirts_XL_1': profile.shirts_XL_1,
            'shirts_XXL_1': profile.shirts_XXL_1,
            'shirts_S_2': profile.shirts_S_2,
            'shirts_M_2': profile.shirts_M_2,
            'shirts_L_2': profile.shirts_L_2,
            'shirts_XL_2': profile.shirts_XL_2,
            'shirts_XXL_2': profile.shirts_XXL_2,
            'shirts_S_3': profile.shirts_S_3,
            'shirts_M_3': profile.shirts_M_3,
            'shirts_L_3': profile.shirts_L_3,
            'shirts_XL_3': profile.shirts_XL_3,
            'shirts_XXL_3': profile.shirts_XXL_3,
        }

    def form_valid(self, form):
        services.change_user_inscription_data(
            user = self.request.user,
            new_data = form.cleaned_data,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        messages.info(self.request, 'Datos modificados correctamente')
        return super(UserProfileEditInscriptionView, self).form_valid(form)


class UserListingsIndexView(TemplateView):
    template_name = 'user_profiles/listings_index.html'


class UserListingView(TemplateView):
    template_name = 'user_profiles/listings_general.html'

    def get(self, *args, **kwargs):
        try:
            listing_id = int(kwargs.get('listing_id', 0))
        except ValueError:
            listing_id = 0

        if listing_id:
            self.listing_data = services.user_listing(listing_id)

        if not listing_id or self.listing_data is None:
            return HttpResponseNotFound('Número de listado incorrecto: %d' % listing_id)

        return super(UserListingView, self).get(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(UserListingView, self).get_context_data(**kwargs)

        (block, rows) = self.listing_data
        context['block'] = block
        context['rows'] = rows

        return context

user_profiles/templates/user_profiles/listings_general.html
<html>
<body>
  {% if rows %}
    <table>
    {% for row in rows %}
      <tr>
      {% for cell in row %}
        <td>{{ cell }}</td>
      {% endfor %}
    {% endfor %}
    </table>
  {% endif %}

  {% if block and rows %}
    <hr>
  {% endif %}

  {% if block %}
    <p>{{ block }}</p>
  {% endif %}
</body>

user_profiles/templates/user_profiles/user_profile_edit_inscription.html
{% extends "dynamic_page.html" %}

{% block dynamic_content %}
<div class="heading">
<h1>Modificar</h1>
</div>
{% comment %}
<p>Aquí puedes modificar cualquier parte de tu información de inscripción, excepto los días
de asistencia. Si deseas cambiar este dato contacta con la organización.</p>
{% endcomment %}
<p><strong>Atención</strong>: si modificas algún dato que influya en el precio de la inscripción
(como el tipo de alojamiento), te agradeceremos que contactes con la organización para ver cómo
podemos compensar la diferencia.</p>

<form method="post" action="{% url 'user-profile-edit-inscription' %}">
  {% csrf_token %}
  <div class="row justify-content-center">
    <div class="col-8">
      <div class="form-group">
        <p title="Indica si vendrás en transporte privado o público, y en este caso, lugar y horario de llegada.">
          <label for="id_notes_transport">¿Cómo vas a venir?</label><br/>
          {{ form.notes_transport }}
          {% if form.notes_transport.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.notes_transport.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          <p title="Indica en qué tipo de habitación te vas a alojar. Si no te sirve ninguna de las opciones, pon 'otros' y contacta con la organización para ver el precio.">
            <label for="id_room_choice">Elige un tipo de alojamiento.</label><br/>
            {{ form.room_choice }}
            {% if form.room_choice.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.room_choice.errors|join:", " }}&nbsp;</b>{% endif %}
          </p>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          <p title="Si prefieres compartir habitación con alguien, o cualquier otro comentario al respecto, indicalo aquí.">
            <label for="id_room_preferences">¿Tienes alguna preferencia sobre con quién compartir habitación?</label>
            {{ form.room_preferences }}
            {% if form.room_preferences.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.room_preferences.errors|join:", " }}&nbsp;</b>{% endif %}
          </p>
        </div>
        <div class="form-group col-md-6">
          <p title="Indica si eres alérgico a algún alimento, vegetariano o cualquier otra condición especial.">
            <label for="id_notes_food">¿Tienes necesidades especiales respecto de las comidas?</label>
            {{ form.notes_food }}
            {% if form.notes_food.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.notes_food.errors|join:", " }}&nbsp;</b>{% endif %}
          </p>
        </div>
      </div>
      <div class="row">
        <div class="form-group col-md-6">
          <p title="Si tienes algúna condición especial (alérgico, vegetariano... elige otros)">
            <label for="id_dinner_menu">El plato principal de la cena de gala:</label>
            {{ form.dinner_menu }}
            {% if form.dinner_menu.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.dinner_menu.errors|join:", " }}&nbsp;</b>{% endif %}
          </p>
        </div>
      </div>
      <div class="form-check">
        <p title="Ayudar a las personas que asisten por primera vez a una EstelCon es una gran idea.">
          {{ form.want_mentor }}
          <label for="id_mentor" class="form-check-label">¿Quieres ser mentora o mentor en esta Estelcon?</label>
          {% if form.mentor.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.mentor.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>

      <div class="form-check">
        <p title="Los escuderos son ayudantes voluntarios para echar una mano a la organización en tareas sencillas.">
          {{ form.squire }}
          <label for="id_squire" class="form-check-label">¿Quieres ser escudero en esta Estelcon?</label>
          {% if form.squire.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.squire.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>


      <div class="form-group">
        <p title="Escribe cualquier otra consideración que nos quieras comentar respecto de tu inscripción.">
          <label for="id_notes_general">¿Alguna otra necesidad que quieras compartir, o comentario?</label>
          {{ form.notes_general }}
          {% if form.notes_general.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.notes_general.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <br/>
      <p>Hay tres tipos de camisetas, unisex, mujer y niño. Para ver cómo es el diseño principal, <a href="#shirt-modal" data-toggle="modal" data-target="#shirt-modal" class="">pulsa aquí</a>.</p>
      <p>Si vas a querer alguna camiseta, indícanos aquí la talla. También puedes, si lo deseas, reservar más de una,
      simplemente indicando la cantidad que quieres en la casilla o casillas correspondientes.</p>
      <p>El precio de las camisetas es de 10€, se entregarán junto con el Maratulmë de la EstelCon, cuando os registréis nada más llegar.</p>
      <p title="Indica cuántas camisetas quieres de cada talla.">
        <div class="row">
          <div class="col-md-2"></div>
          <div class="col-md-2">
            <label for="id_shirts_S_1">Camisetas talla S: </label>
          </div>
          <div class="col-md-2">
            <label for="id_shirts_M_1">Camisetas talla M: </label>
          </div>
          <div class="col-md-2">
            <label for="id_shirts_L_1">Camisetas talla L: </label>
          </div>
          <div class="col-md-2">
            <label for="id_shirts_XL_1">Camisetas talla XL: </label>
          </div>
          <div class="col-md-2">
              <label for="id_shirts_XXL_1">Camisetas talla XXL: </label>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            Unisex
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_S_1 }}
            {% if form.shirts_S_1.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_S_1.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_M_1 }}
            {% if form.shirts_M_1.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_M_1.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_L_1 }}
            {% if form.shirts_L_1.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_L_1.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XL_1 }}
            {% if form.shirts_XL_1.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XL_1.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XXL_1 }}
            {% if form.shirts_XXL_1.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XXL_1.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            Mujer
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_S_2 }}
            {% if form.shirts_S_2.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_S_2.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_M_2 }}
            {% if form.shirts_M_2.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_M_2.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_L_2 }}
            {% if form.shirts_L_2.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_L_2.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XL_2 }}
            {% if form.shirts_XL_2.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XL_2.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XXL_2 }}
            {% if form.shirts_XXL_2.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XXL_2.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            Niño
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_S_3 }}
            {% if form.shirts_S_3.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_S_3.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_M_3 }}
            {% if form.shirts_M_3.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_M_3.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_L_3 }}
            {% if form.shirts_L_3.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_L_3.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XL_3 }}
            {% if form.shirts_XL_3.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XL_3.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
          <div class="form-group col-md-2">
            {{ form.shirts_XXL_3 }}
            {% if form.shirts_XXL_3.errors %} <b style="color:white;background-color:red">&nbsp;{{ form.shirts_XXL_3.errors|join:", " }}&nbsp;</b>{% endif %}<br/>
          </div>
        </div>
      </p>
      <br/>
      <p>
        <input type="submit" value="enviar" class="btn btn-template-outlined"/>
        <a href="{% url 'user-profile' %}" class="btn btn-template-outlined">Cancelar</a>
      </p>
    </div>
  </div>
</form>
{% endblock %}