activities/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required, user_passes_test
from django.conf import settings

from .views import (
    ScheduleHiddenView, ScheduleRealView, ActivityView, ActivitySubscribeView, ActivityEditView, ProposalView, ProposalSentView
)


def user_is_staff(user):
    return user.is_staff


if settings.SCHEDULE_HIDDEN:
    urlpatterns = [
        # Option initial (schedule is hidden, visible only to admin)
        url(r'^programa$', ScheduleHiddenView.as_view(), name='schedule'),
        url(r'^programa-desarrollo$', user_passes_test(user_is_staff)(ScheduleRealView.as_view()), name='schedule-devel'),
    ]
else:
    urlpatterns = [
        # Option normal (schedule is publicly visible)
        url(r'^programa$', ScheduleRealView.as_view(), name='schedule'),
    ]

urlpatterns += [
    url(r'^actividad/(?P<activity_id>\d+)$', ActivityView.as_view(), name='activity'),
    url(r'^actividad-inscribir/(?P<activity_id>\d+)$', login_required(ActivitySubscribeView.as_view()), name='activity-subscribe'),
    url(r'^actividad-editar/(?P<activity_id>\d+)$', login_required(ActivityEditView.as_view()), name='activity-edit'),
    url(r'^propuesta$', login_required(ProposalView.as_view()), name='proposal'),
    url(r'^propuesta-enviada$', login_required(ProposalSentView.as_view()), name='proposal-sent'),
]

activities/models.py
from django.db import models

from user_profiles.models import User


class Activity(models.Model):
    title = models.CharField('Título', max_length=100)
    subtitle = models.TextField('Entradilla', blank = True)
    text = models.TextField('Descripción', blank = True)
    start = models.DateTimeField('Empieza en', blank = True, null = True)
    end = models.DateTimeField('Termina en', blank = True, null = True)
    column = models.IntegerField('Columna', default = 0,
        choices = (
            (0, 'Ancho completo'),
            (1, 'Columna 1'),
            (2, 'Columna 2')
        )
    )
    duration = models.CharField('Duración aproximada', max_length = 50)
    max_places = models.IntegerField('Nº máximo de plazas', default = 0)
    logistics = models.TextField('Necesidades logísticas', blank = True)
    notes_organization = models.TextField('Comentarios', blank = True)
    has_view_page = models.BooleanField('Tiene página propia', default = False)
    show_owners = models.BooleanField('Mostrar responsables', default = False)
    requires_inscription = models.BooleanField('Requiere inscripción', default = False)

    owners = models.ManyToManyField(User, verbose_name = 'Responsables', related_name = 'owner_of')
    organizers = models.ManyToManyField(User,
                                        verbose_name = 'Organizadores',
                                        related_name = 'organizer_of',
                                        blank = True)
    participants = models.ManyToManyField(User,
                                          verbose_name = 'Participantes',
                                          related_name = 'participant_of',
                                          blank = True)

    class Meta:
        verbose_name = 'Actividad'
        verbose_name_plural = 'Actividades'
        ordering = ['start', 'end']

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('activity', kwargs={'activity_id': self.id})

    def day_start(self):
        if self.start == None:
            return ' SIN HORARIO'
        else:
            import locale
            locale.setlocale(locale.LC_ALL, 'es_ES.UTF-8')
            return self.start.strftime('%A')

    def hour_start(self):
        if self.start == None:
            return ''
        elif self.start.hour == 0 and self.start.minute == 0 and self.start.second == 0 and \
             self.end != None and self.end.hour == 0 and self.end.minute == 0 and self.end.second == 0:
            return ''
        else:
            return self.start.strftime('%H:%M')

    def hour_end(self):
        if self.end == None:
            return ''
        elif self.start != None and self.start.hour == 0 and self.start.minute == 0 and self.start.second == 0 and \
             self.end.hour == 0 and self.end.minute == 0 and self.end.second == 0:
            return ''
        else:
            return self.end.strftime('%H:%M')

    def __str__(self):
        return '%s %s - %s' % (self.day_start(), self.hour_start(), self.title)

activities/forms.py
from django import forms
from .models import Activity


class ActivitySubscribeForm(forms.Form):
    id = forms.IntegerField(
        min_value = 0, required=True,
        widget = forms.HiddenInput,
    )
    title = forms.CharField(
        max_length=100, required=True,
        widget = forms.HiddenInput,
    )


class ProposalForm(forms.Form):
    title = forms.CharField(
        max_length=100, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    subtitle = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    duration = forms.CharField(
        max_length=50, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    max_places = forms.IntegerField(
        min_value = 0, required=True, initial = 0,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    show_owners = forms.BooleanField(
        initial = False, required = False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    requires_inscription = forms.BooleanField(
        initial = False, required = False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    owners = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    organizers = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    text = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    logistics = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    notes_organization = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )


class ActivityForm(forms.ModelForm):
    title = forms.CharField(
        max_length=100, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    subtitle = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    text = forms.CharField(
        required = True,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    duration = forms.CharField(
        max_length=50, required=True,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    max_places = forms.IntegerField(
        min_value = 0, required=True, initial = 0,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    show_owners = forms.BooleanField(
        initial = False, required = False,
        widget=forms.CheckboxInput(attrs={'class': 'form-check-input'}),
    )
    logistics = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )
    notes_organization = forms.CharField(
        required = False,
        widget = forms.Textarea(attrs={'class': 'form-control'}),
    )

    class Meta:
        model = Activity
        fields = ['id', 'title', 'subtitle', 'duration', 'max_places', 'show_owners', 'text', 'logistics', 'notes_organization']

activities/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic.base import TemplateView
from django.views.generic.edit import FormView, UpdateView
from django.urls import reverse_lazy
from django.contrib import messages
from django.conf import settings

from . import services

from .models import Activity

from .forms import (
    ActivitySubscribeForm, ProposalForm, ActivityForm
)


class ScheduleHiddenView(TemplateView):
    template_name = 'activities/schedule_hidden.html'


class ScheduleRealView(TemplateView):
    template_name = 'activities/schedule_real.html'

    def get_context_data(self, **kwargs):
        context = super(ScheduleRealView, self).get_context_data(**kwargs)
        (activ_without_hour, days) = services.get_schedule()
        context['activ_without_hour'] = activ_without_hour
        context['days'] = days
        return context


class ActivityView(TemplateView):
    template_name = 'activities/activity.html'

    def get(self, request, *args, **kwargs):
        (self.activity, self.user_status) = services.get_activity_and_status(kwargs['activity_id'], self.request.user)
        return super(ActivityView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ActivityView, self).get_context_data(**kwargs)

        context['activity'] = self.activity
        if self.activity:
            context['is_owner'] = self.user_status['is_owner']
            context['is_organizer'] = self.user_status['is_organizer']
            context['is_participant'] = self.user_status['is_participant']
            context['is_admin'] = self.user_status['is_admin']

        return context


class ActivitySubscribeView(FormView):
    template_name = 'activities/activity_subscribe.html'
    form_class = ActivitySubscribeForm
    success_url = reverse_lazy('user-profile')

    def dispatch(self, request, *args, **kwargs):
        (self.activity, self.user_status) = services.get_activity_and_status(kwargs['activity_id'], self.request.user)
        return super(ActivitySubscribeView, self).dispatch(request, *args, **kwargs)

    def get_initial(self):
        return {
            'id': self.activity.id if self.activity else 0,
            'title': self.activity.title if self.activity else '',
        }

    def get_context_data(self, **kwargs):
        context = super(ActivitySubscribeView, self).get_context_data(**kwargs)

        context['activity'] = self.activity
        if self.activity \
                and self.activity.requires_inscription \
                and not self.user_status['is_owner'] \
                and not self.user_status['is_organizer'] \
                and not self.user_status['is_participant']:
            context['can_subscribe'] = True
        else:
            context['can_subscribe'] = False

        return context

    def form_valid(self, form):
        services.subscribe_to_activity(
            user = self.request.user,
            activity_id = form.cleaned_data['id'],
        )
        messages.info(self.request, 'Te has inscrito en la actividad.')
        return super(ActivitySubscribeView, self).form_valid(form)


class ActivityEditView(UpdateView):
    template_name = 'activities/activity_edit.html'
    model = Activity
    form_class = ActivityForm
    pk_url_kwarg = 'activity_id'

    def form_valid(self, form):
        result = super(ActivityEditView, self).form_valid(form)
        services.change_activity(
            user = self.request.user,
            activity = self.object,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        messages.info(self.request, 'Datos modificados correctamente')
        return result

    def get_success_url(self):
        return reverse_lazy('activity', args=[self.object.id])


class ProposalSentView(TemplateView):
    template_name = 'activities/proposal_sent.html'


class ProposalView(FormView):
    template_name = 'activities/proposal.html'
    form_class = ProposalForm
    success_url = reverse_lazy('proposal-sent')

    def form_valid(self, form):
        services.send_proposal(
            user = self.request.user,
            data = form.cleaned_data,
            home_url = settings.PROTOCOL + '://' + settings.SITE_URL,
        )
        messages.info(self.request, 'Se ha enviado la propuesta a los organizadores.')
        return super(ProposalView, self).form_valid(form)


class ProposalSentView(TemplateView):
    template_name = 'activities/proposal_sent.html'

activities/templates/activities/activity.html
{% extends "dynamic_page.html" %}

{% block dynamic_content %}
<div class="heading">
  <h1>Actividad</h1>
</div>
{% if messages %}
  {% for message in messages %}
    <h3 class="message">{{ message }}</h3>
  {% endfor %}
{% endif %}

{% if not activity %}

  <p>No se encuentra la actividad.</p>

{% else %}
<div class="row">
  <div class="col-6">
    {% if is_owner %}
      <div class="alert alert-primary" role="alert">(Eres el RESPONSABLE de esta actividad. Puedes ver toda la información y además modificarla.)</div>
    {% endif %}
    {% if is_organizer %}
      <div class="alert alert-primary" role="alert">(Eres un ORGANIZADOR de esta actividad. Puedes ver toda la información.)</div>
    {% endif %}
    {% if is_participant %}
      <div class="alert alert-secondary" role="alert">(Estás inscrito en esta actividad.)</div>
    {% endif %}

    {% if is_owner %}
      <a href="/actividad-editar/{{ activity.id }}" class="btn btn-template-outlined">Modificar datos de esta actividad</a>
      <hr>
    {% endif %}

    <h2>{{ activity.title }}</h2>
    {% if activity.subtitle %}
      <h3>{{ activity.subtitle }}</h3>
    {% endif %}

    {% if activity.show_owners and activity.owners.all %}
      Coordinada por: <em>
      {% for owner in activity.owners.all %}
        {% if not forloop.first and not forloop.last %}, {% endif %}
        {% if not forloop.first and forloop.last %} y {% endif %}
        {{ owner.get_full_name }} {% if owner.profile.alias %}"{{ owner.profile.alias }}"{% endif %}
      {% endfor %}
      </em>
    {% endif %}

    {% if activity.text %}
      <p>{{ activity.text|safe|linebreaks }}</p>
    {% endif %}

    {% if is_owner or is_organizer or is_admin %}

      {% if activity.duration %}
      <h4>Duración: {{ activity.duration }}.</h4>
      {% endif %}

      {% if activity.max_places %}
      <h4>Nº máximo de plazas: {{ activity.max_places }}.</h4>
      {% endif %}

      {% if activity.logistics %}
        <h4>Necesidades logísticas:</h4>
        <p>{{ activity.logistics|linebreaks }}</p>
      {% endif %}

      {% if activity.notes_organization %}
        <h4>Comentarios de o hacia la organización:</h4>
        <p>{{ activity.notes_organization|linebreaks }}</p>
      {% endif %}

    {% endif %}
  </div>

  <div class="col-6">
    {% if is_owner or is_organizer or is_admin %}
      {% if activity.owners.all %}
        <h4>Responsables:</h4>
        <p>
        {% for owner in activity.owners.all %}
          <a href="mailto:{{ owner.email }}">
            {{ owner.get_full_name }} {% if owner.profile.alias %}"{{ owner.profile.alias }}"{% endif %}
          </a><br/>
        {% endfor %}
        </p>
      {% endif %}

      {% if activity.organizers.all %}
        <h4>Organizadores:</h4>
        <p>
          {% for organizer in activity.organizers.all %}
            <a href="mailto:{{ organizer.email }}">
              {{ organizer.get_full_name }} {% if organizer.profile.alias %}"{{ organizer.profile.alias }}"{% endif %}
            </a><br/>
          {% endfor %}
        </p>
      {% endif %}

      {% if activity.participants.all %}
        <h4>Lista de personas inscritas:</h4>
        <p>
          {% for participant in activity.participants.all %}
            <a href="mailto:{{ participant.email }}">
              {{ participant.get_full_name }} {% if participant.profile.alias %}"{{ participant.profile.alias }}"{% endif %}
            </a><br/>
          {% endfor %}
        </p>
        <p>Para enviar un mail a todos (se recomienda poner las direcciones en copia oculta, CCO o BCC):</p>
        <p><textarea class="form-control" rows="3">{% for participant in activity.participants.all %}{% if not forloop.first %}, {% endif %}{{ participant.email }}{% endfor %}</textarea></p>
      {% endif %}
    {% endif %}
    {% if activity.requires_inscription and not is_owner and not is_organizer and not is_participant %}
      <p>Esta actividad necesita que te inscribas previamente antes de poder participar, puesto que sus
      organizadores deben saber cuánta gente la quiere realizar.<p>
      <a href="/actividad-inscribir/{{ activity.id }}" class="btn btn-template-outlined">Inscribirte en la actividad</a>
    {% endif %}
  </div>
</div>
{% endif %}
<hr>
<a href="/programa" class="btn btn-template-outlined">Volver atrás</a></div>

{% endblock %}

activities/templates/activities/activity_edit.html
{% extends "dynamic_page.html" %}

{% block dynamic_content %}
<div class="heading">
<h1>Modificar actividad</h1>
</div>
{% if message %}

<p class="message">{{ message }}</p>

{% else %}

<p>Aquí puedes modificar los datos de la actividad.</p>

<p>Si quieres cambiar algo que no se encuentra aquí, envíanos un mensaje o pidelo en el
recuadro de comentarios para la organización de la EC.</p>

<p>MANTÉN INMÓVIL DURANTE 1 SEG. EL CURSOR DEL RATÓN SOBRE LOS RECUADROS DE TEXTO PARA OBTENER MÁS INFORMACIÓN.</p>

<form method="post" action="{% url 'activity-edit' activity_id=activity.id %}">
  {% csrf_token %}
  {{ form.id }}
  <div class="row justify-content-center">
    <div class="col-12">
      <div class="form-group">
        <p title="Descripción breve en una línea, tal como aparecerá en el Programa.">
          <label for="id_title">Título de la actividad: *</label><br/>
          {{ form.title }}
          {% if form.title.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.title.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
      <p title="Un comentario breve, en una o dos líneas, que aparecerá debajo del título.">
        <label for="id_subtitle">Entradilla:</label><br/>
        {{ form.subtitle }}
        {% if form.subtitle.errors %}<br/><b style="color:white;background-color=red">&nbsp;{{ form.subtitle.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-group">
      <p title="La duración prevista para la actividad, o 0 si es indefinida.">
        <label for="id_duration">Duración aproximada: *</label><br/>
        {{ form.duration }}
        {% if form.duration.errors %}<br/><b style="color:white;background-color=red">&nbsp;{{ form.duration.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-group">
      <p title="Indica cuántas personas podrán apuntarse como máximo, o 0 si no hay límite.">
        <label for="id_max_places">Nº máximo de plazas (si lo hay): *</label><br/>
        {{ form.max_places }}
        {% if form.max_places.errors %}<br/><b style="color:white;background-color=red">&nbsp;{{ form.max_places.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-check">
      <p title="Indica si se mostrará en el Programa el nombre de los responsables.">
        {{ form.show_owners }}
        <label for="id_show_owners" class="form-check-label">Mostrar responsables: </label>
        {% if form.show_owners.errors %}<br/><b style="color:white;background-color=red">&nbsp;{{ form.show_owners.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-group">
      <p title="Describe la actividad con el detalle que quieras. Se mostrará en el Programa detallado.">
        <label for="id_text">Descripción: *</label><br/>
        {{ form.text }}
        {% if form.text.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.text.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-group">
      <p title="Dinos qué necesidades tienes. Esto sólo lo verá la organización de la EC.">
        <label for="id_logistics">Necesidades logísticas (materiales, espacio y cualquier otro recurso necesario):</label><br/>
        {{ form.logistics }}
        {% if form.logistics.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.logistics.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>
    <div class="form-group">
      <p title="Coméntanos cualquier otra cosa que se te ocurra, sólo para verlo nosotros.">
        <label for="id_notes_organization">Comentarios para la organización de la EC:</label><br/>
        {{ form.notes_organization }}
        {% if form.notes_organization.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.notes_organization.errors|join:", " }}&nbsp;</b>{% endif %}
      </p>
    </div>

    <input type="submit" value="enviar" class="btn btn-primary btn-lg"/>
  </div>
</div>

</form>

{% endif %}

{% endblock %}

activities/templates/activities/proposal.html
{% extends "dynamic_page.html" %}

{% block dynamic_content %}
<div class="heading">
  <h1>Propuesta de actividad</h1>
</div>
{% if messages %}
    {% for message in messages %}
        <h3 class="message">{{ message }}</h3>
    {% endfor %}
{% endif %}

<p>¿Quieres organizar una actividad? ¡Proponla y te buscaremos un hueco!</p>

<p>Rellena este formulario y envíanoslo. Rellena las casillas con el mayor detalle que puedas.
Una vez aceptada y asignada un horario, la actividad aparecerá en el Programa de actividades, y tendrá su propia ficha, rellena con los datos que nos has pasado.
Más adelante podrás modificar cualquiera de estos datos desde tu ficha personal.</p>

<p><strong>Ten en cuenta que en este evento, las actividades más adecuadas serán las que tengan un
caracter abierto al público, de manera que si tienes alguna pequeña obra de teatro, alguna conferencia
de carácter divulgativo, o algún taller vistoso y simpático, serán bienvenidas y celebradas.</strong></p>

<p>Indicanos la duración prevista y si hay un tope máximo de plazas. También si es una actividad
que requiere inscripción. Si es así, los demás asistentes a la EstelCon podrán inscribirse y podrás
consultar en todo momento quienes están apuntados.</p>

<p>Debes indicar también si hay más responsables y organizadores. Los responsables tendrán
permiso para modificar la ficha de la actividad. Y los organizadores son todas las demás personas
involucradas en la organización, que podrán consultar la ficha completa y la lista de inscritos,
si la hay, pero no modificar nada.</p>

{% comment %}
<p>Si quieres vender artículos en la <b>Esteltienda</b>, puedes usar también este formulario. Indica
"Esteltienda" en el título, y usa la descripción y los campos que necesites para explicar los
artículos a vender y cualquier otro comentario.</p>
{% endcomment %}

<p>MANTÉN INMÓVIL DURANTE 1 SEG. EL CURSOR DEL RATÓN SOBRE LOS RECUADROS DE TEXTO PARA OBTENER MÁS INFORMACIÓN.</p>

<form method="post" action="{% url 'proposal' %}">
  {% csrf_token %}
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <p title="Descripción breve en una línea, tal como aparecerá en el Programa.">
          <label for="id_title">Título de la actividad: *</label><br/>
          {{ form.title }}
          {% if form.title.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.title.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="Un comentario breve, en una o dos líneas, que aparecerá debajo del título.">
          <label for="id_subtitle">Entradilla:</label><br/>
          {{ form.subtitle }}
          {% if form.subtitle.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.subtitle.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="La duración prevista para la actividad, o 0 si es indefinida.">
          <label for="id_duration">Duración aproximada: *</label><br/>
          {{ form.duration }}
          {% if form.duration.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.duration.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="Indica cuántas personas podrán apuntarse como máximo, o 0 si no hay límite.">
          <label for="id_max_places">Nº máximo de plazas (si lo hay):</label><br/>
          {{ form.max_places }}
          {% if form.max_places.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.max_places.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-check">
        <p title="Indica si se mostrará en el Programa el nombre de los responsables.">
            {{ form.show_owners }}
            <label for="id_show_owners" class="form-check-label">Mostrar responsables</label>
          {% if form.show_owners.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.show_owners.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-check">
        <p title="Indica si será necesario inscribirse previamente para participar en esta actividad.">
            {{ form.requires_inscription }}
            <label for="id_requires_inscription" class="form-check-label">Requiere inscripción </label>
          {% if form.requires_inscription.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.requires_inscription.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="Entre una y tres personas que representan la actividad y podrán modificar estos datos.">
          <label for="id_owners">Responsable(s) además de ti (nombre y apellidos, pseudónimo y/o nombre de usuario en esta web): </label><br/>
          {{ form.owners }}
          {% if form.owners.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.owners.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
          <p title="Todas las demás personas que colaborarán en organizar esta actividad.">
            <label for="id_organizers">Otros organizadores: </label><br/>
            {{ form.organizers }}
            {% if form.organizers.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.organizers.errors|join:", " }}&nbsp;</b>{% endif %}
          </p>
        </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <p title="Describe la actividad con el detalle que quieras. Se mostrará en el Programa detallado.">
          <label for="id_text">Descripción: *</label><br/>
          {{ form.text }}
          {% if form.text.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.text.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="Dinos qué necesidades tienes. Esto sólo lo verá la organización de la EC.">
          <label for="id_logistics">Necesidades logísticas (materiales, espacio y cualquier otro recurso necesario):</label><br/>
          {{ form.logistics }}
          {% if form.logistics.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.logistics.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>
      <div class="form-group">
        <p title="Coméntanos cualquier otra cosa que se te ocurra, sólo para verlo nosotros.">
          <label for="id_notes_organization">Comentarios para la organización de la EC:</label><br/>
          {{ form.notes_organization }}
          {% if form.notes_organization.errors %}<br/><b style="color:white;background-color:red">&nbsp;{{ form.notes_organization.errors|join:", " }}&nbsp;</b>{% endif %}
        </p>
      </div>  
    </div>
  </div>
  <p>
    <input type="submit" value="enviar" class="btn btn-primary btn-lg"/>
  </p>
</form>

{% endblock %}

activities/templates/activities/proposal_sent.html
{% extends "dynamic_page.html" %}

{% block dynamic_content %}
<div class="heading">
    <h1>Propuesta de actividad</h1>
</div>
{% if messages %}
    {% for message in messages %}
        <h3 class="message">{{ message }}</h3>
    {% endfor %}
{% endif %}

<p>Estudiaremos la actividad que propones y le buscaremos un hueco en la Estelcon. En cuanto
lo hagamos, podrás ver cómo aparece en el Programa de actividades,
incluyendo una ficha rellena con los datos que nos has enviado (al menos con la parte pública).
Y si tú o cualquiera de las personas designadas como responsables accedéis a la web con vuestro
usuario y contraseña, podréis consultar y modificar todos los datos.</p>

<p>Si tenemos alguna duda o consulta que hacerte, contactaremos contigo a través del correo
electrónico o el teléfono que indicaste al registrarte.</p>

<p>¡Muchas gracias por participar! Entre todos haremos una gran Mereth Aderthad.</p>

{% endblock %}